buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.gradle.jdks:gradle-jdks-settings:0.67.0'
    }
}
apply plugin: 'com.palantir.jdks.settings'
rootProject.name = 'conjure-java-runtime-api'

include 'errors'
include 'service-config'
include 'ssl-config'
include 'test-utils'
include 'extras:jackson-support'
