
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'org.revapi.revapi-gradle-plugin'

dependencies {
    api project(":errors")

    api "org.assertj:assertj-core"
    api "org.mockito:mockito-core", {
        exclude module: 'byte-buddy-agent'
    }

    testImplementation 'org.junit.jupiter:junit-jupiter'
}
